# single git
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/banulp/configFiles
#          skipSslValidation: true
# composit
spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          -
            type: git
            uri: https://github.com/banulp/configFiles
            skipSslValidation: true
          -
            type: git
            uri: https://github.com/banulp/configRepos
            skipSslValidation: true